// Builds the product lists of the menu pages (menu/*.html) from the data files in menu-data/,
// and the coffee prices on the homepage (index.html and ro.html).
//
//   node scripts/build-menu.js           rewrites the pages
//   node scripts/build-menu.js --check   only lists the pages that differ from the data
//
// Each menu page has one generated block, between the two marker comments below. Everything
// outside the markers (page header, page title, footer) is still edited by hand in the page.
// Needs Node.js only, no packages.

"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const DATA_DIR = path.join(ROOT, "menu-data");
const MENU_DIR = path.join(ROOT, "menu");
const HOMEPAGES = ["index.html", "ro.html"];

const START = "<!-- Products: generated by scripts/build-menu.js from menu-data/";
const END = "<!-- End of generated products -->";
const ICONS = "img/icons_watermarked/webp/";
const PHOTOS = "img/big_watermarked/webp/";

const TEXT = {
  ingredients: "Ingredients:",
  nutrition: "Nutritional values per product:",
  energy: "Energy (kJ/kcal):",
  fat: "Fat (g):",
  saturates: "– of which saturates (g):",
  carbs: "Carbohydrates (g):",
  sugars: "– of which sugars (g):",
  protein: "Protein (g):",
  salt: "Salt (g):",
  allergens: "Allergens:",
  glass: "Glass",
  currency: "ron",
  photoAlt: "at Hypso25",
};

// ---------------------------------------------------------------- HTML helpers

// Data text is HTML, so <b> and <wbr> work, but a plain "&" is fine and is escaped here.
function html(text) {
  return String(text).replace(/&(?!#?\w+;)/g, "&amp;");
}

function attr(text) {
  return html(text).replace(/"/g, "&quot;");
}

function plain(text) {
  return String(text).replace(/<[^>]+>/g, "");
}

function classAttr(names) {
  const list = names.filter(Boolean).join(" ");
  return list ? ` class="${list}"` : "";
}

function styleAttr(style) {
  return style ? ` style="${style}"` : "";
}

function indent(lines, spaces) {
  const pad = " ".repeat(spaces);
  return lines.map((line) => pad + line);
}

function small(content) {
  return `<p class="m-0" style="font-size: small">${content}</p>`;
}

// ---------------------------------------------------------------- page parts

function productName(product) {
  return html(product.name) + (product.ml ? ` - ${product.ml}ml` : "");
}

function priceBubble(product, look) {
  return [
    `<p class="menu-price h5 font-weight-normal${look.price ? " " + look.price : ""}"${styleAttr(look.priceStyle)}>`,
    `  <b>${product.price}</b> <span style="font-size: small"><b>${TEXT.currency}</b></span>`,
    "</p>",
  ];
}

function nutritionLines(n, layout) {
  const energy = `<b>${TEXT.energy}</b> ${n.kj} / ${n.kcal}`;
  const fat = `<b>${TEXT.fat}</b> ${n.fat} <b>${TEXT.saturates}</b> ${n.saturates}`;
  const carbs = `<b>${TEXT.carbs}</b> ${n.carbs} <b>${TEXT.sugars}</b> ${n.sugars}`;
  const protein = `<b>${TEXT.protein}</b> ${n.protein}; <b>${TEXT.salt}</b> ${n.salt}`;
  const header = small(`<b>${TEXT.nutrition}</b>`);

  if (layout === "compact") {
    return [header, small(`${energy}; ${fat}`), small(`${carbs}; ${protein}`)];
  }
  return [header, small(energy), small(fat), small(carbs), small(protein)];
}

// A line under the product name: "text" is a normal paragraph, { tight: "text" } has no space
// below it, { small: "text" } is in the small print used for ingredients.
function freeLine(line) {
  if (typeof line === "string") {
    return `<p>${html(line)}</p>`;
  }
  if ("tight" in line) {
    return `<p class="m-0">${html(line.tight)}</p>`;
  }
  if ("small" in line) {
    return small(html(line.small));
  }
  throw new Error("Unknown line: " + JSON.stringify(line));
}

function productDetails(product, look) {
  const lines = [`<h4${classAttr([look.name ?? "mb-0"])}>${productName(product)}</h4>`];

  (product.lines || []).forEach((line) => lines.push(freeLine(line)));
  if (product.glass) {
    lines.push(`<p class="m-0">${TEXT.glass} ${product.glass.ml}ml: ${product.glass.price} ${TEXT.currency}</p>`);
  }
  if (product.ingredients) {
    lines.push(small(`<b>${TEXT.ingredients}</b> ${html(product.ingredients)}`));
  }
  if (product.nutrition) {
    lines.push(...nutritionLines(product.nutrition, look.nutrition));
  }
  if (product.note) {
    lines.push(small(html(product.note)));
  }
  if (product.allergens) {
    lines.push(small(`<b>${TEXT.allergens}</b> ${html(product.allergens)}`));
  }
  if (lines.length === 1 && look.emptyLine != null) {
    lines.push(`<p${classAttr([look.emptyLine])}></p>`);
  }
  return lines;
}

function productRow(product, look, space) {
  if (!product.photo) {
    // Price-only row, without a photo.
    const row = look.row || `row container align-items-center${space ? " mb-5" : ""} pr-0`;
    return [
      `<div class="${row}"${styleAttr(look.rowStyle)}>`,
      `  <div class="${look.priceColumn || "col-1"}" style="margin-left: 20px">`,
      ...indent(priceBubble(product, look), 4),
      "  </div>",
      '  <div class="col">',
      ...indent(productDetails(product, look), 4),
      "  </div>",
      "</div>",
    ];
  }

  const alt = product.alt || `${plain(product.name)} ${TEXT.photoAlt}`;
  const image = `<img class="w-100 rounded-circle mb-3 mb-sm-0" src="${ICONS}${product.photo}" alt="${attr(alt)}" />`;
  // No space between the link and the photo, so nothing but the photo is inside the link.
  const photo = product.big
    ? [`<a href="${PHOTOS}${product.big}" target="_blank" rel="noopener noreferrer">${image}</a>`]
    : [image];

  return [
    `<div class="row align-items-center${space ? " mb-5" : ""}">`,
    '  <div class="col-4 col-sm-3">',
    ...indent(photo, 4),
    ...indent(priceBubble(product, look), 4),
    "  </div>",
    '  <div class="col-8 col-sm-9">',
    ...indent(productDetails(product, look), 4),
    "  </div>",
    "</div>",
  ];
}

// A named list without a price, like the syrup flavours on the coffee page.
function listRow(item, last) {
  return [
    '<div class="row align-items-center">',
    '  <div class="col-1"></div>',
    '  <div class="col">',
    `    <h4 class="mb-0">${html(item.list)}</h4>`,
    `    <p class="${last ? "mb-5" : "mb-0"}">${html(item.text)}</p>`,
    ...(item.allergens ? ["    " + small(`<b>${TEXT.allergens}</b> ${html(item.allergens)}`)] : []),
    "  </div>",
    "</div>",
  ];
}

function sectionLines(section, pageLook, lastSection) {
  const look = { ...pageLook, ...section.look };
  const lines = [`<h3${classAttr(["h2 font-weight-bold", look.heading ?? "mb-0"])}>${html(section.title)}</h3>`];

  const intro = [].concat(section.intro || []);
  intro.forEach((text, i) => {
    const last = i === intro.length - 1;
    lines.push(`<p${classAttr([last ? look.intro ?? "mb-5" : "mb-0"])}>${html(text)}</p>`);
  });

  const items = section.items || [];
  const lastList = items.map((item) => Boolean(item.list)).lastIndexOf(true);
  items.forEach((item, i) => {
    if (item.list) {
      lines.push(...listRow(item, i === lastList));
      return;
    }
    const itemLook = { ...look, ...item.look };
    const lastOnPage = lastSection && i === items.length - 1;
    const space = itemLook.space ?? !(lastOnPage && !look.spaceAfterLast);
    lines.push(...productRow(item, itemLook, space));
  });
  return lines;
}

function pageBlock(data) {
  const columnClass = data.columns.length === 1 ? "col-lg-12" : "col-lg-6";
  const lines = ['<div class="row">'];
  data.columns.forEach((sections, c) => {
    lines.push(`  <div class="${columnClass}">`);
    sections.forEach((section, s) => {
      const lastSection = c === data.columns.length - 1 && s === sections.length - 1;
      lines.push(...indent(sectionLines(section, data.look || {}, lastSection), 4));
    });
    lines.push("  </div>");
  });
  lines.push("</div>");
  return lines;
}

// ---------------------------------------------------------------- files

function replaceBlock(source, dataFile, lines) {
  const eol = source.includes("\r\n") ? "\r\n" : "\n";
  const start = source.indexOf(START);
  const end = source.indexOf(END);
  if (start < 0 || end < start) {
    throw new Error("the generated-block markers are missing");
  }
  const lineStart = source.lastIndexOf("\n", start) + 1;
  const pad = source.slice(lineStart, start);
  const block = [
    `${START}${dataFile}. Edit that file, not this block. -->`,
    ...lines,
    END,
  ].map((line, i) => (i === 0 ? line : pad + line));
  return source.slice(0, start) + block.join(eol) + source.slice(end + END.length);
}

function findProduct(pages, name) {
  for (const data of pages) {
    for (const sections of data.columns) {
      for (const section of sections) {
        const product = (section.items || []).find((item) => item.name === name);
        if (product) {
          return product;
        }
      }
    }
  }
  throw new Error(`homepage price: no product named "${name}"`);
}

// Homepage coffee list: each label's price is the sum of the listed menu products,
// e.g. Decaf = Espresso + the decaf supplement.
function updateHomepage(source, prices) {
  let result = source;
  for (const [label, total] of Object.entries(prices)) {
    const escaped = html(label).replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const pattern = new RegExp(`(<dt>${escaped}</dt>\\s*<dd>)\\d+( ${TEXT.currency}</dd>)`, "g");
    const count = (result.match(pattern) || []).length;
    if (count !== 1) {
      throw new Error(`homepage price "${label}" found ${count} times`);
    }
    result = result.replace(pattern, `$1${total}$2`);
  }
  return result;
}

function main() {
  const check = process.argv.includes("--check");
  const dataFiles = fs.readdirSync(DATA_DIR).filter((name) => name.endsWith(".js")).sort();
  const pages = dataFiles.map((name) => ({ ...require(path.join(DATA_DIR, name)), dataFile: name }));
  const outputs = [];

  for (const data of pages) {
    const file = path.join(MENU_DIR, data.page);
    const source = fs.readFileSync(file, "utf8");
    try {
      outputs.push({ file, source, result: replaceBlock(source, data.dataFile, pageBlock(data)) });
    } catch (error) {
      throw new Error(`menu/${data.page}: ${error.message}`);
    }
  }

  const homePrices = {};
  for (const data of pages) {
    for (const [label, names] of Object.entries(data.homepage || {})) {
      homePrices[label] = names.reduce((sum, name) => sum + Number(findProduct(pages, name).price), 0);
    }
  }
  for (const name of HOMEPAGES) {
    const file = path.join(ROOT, name);
    const source = fs.readFileSync(file, "utf8");
    outputs.push({ file, source, result: updateHomepage(source, homePrices) });
  }

  const changed = outputs.filter((output) => output.result !== output.source);
  for (const output of changed) {
    const name = path.relative(ROOT, output.file).replace(/\\/g, "/");
    if (check) {
      console.log(`out of date: ${name}`);
    } else {
      fs.writeFileSync(output.file, output.result);
      console.log(`updated: ${name}`);
    }
  }
  if (!changed.length) {
    console.log("All menu pages match the data.");
  }
  if (check && changed.length) {
    process.exitCode = 1;
  }
}

main();
