window.hypsoReviewLinks = {
  googleMore:
    "https://www.google.com/search?sca_esv=7f84a317695edff8&rlz=1C1GCEA_en-GBRO1182RO1182&q=HYPSO25+Reviews&rflfq=1&num=20&stick=H4sIAAAAAAAAAONgkxI2sjA1sDA2NzQztzQ0NTO3MDQx3cDI-IqR3yMyINjfyFQhKLUsM7W8eBEruggAJwq8fj4AAAA&rldimm=2850837167915678145&tbm=lcl&hl=en-RO&sa=X&ved=2ahUKEwj-qMDY2oKVAxX2xwIHHRSrHJkQ9fQKegQIMxAG&biw=2560&bih=1271&dpr=1#lkt=LocalPoiReviews",
  tripadvisorMore:
    "https://www.tripadvisor.com/Restaurant_Review-g295396-d17560953-Reviews-Hypso25-Constanta_Constanta_County_Southeast_Romania.html",
};

window.hypsoReviews = {
  google: [
    {
      author: "Jackie",
      rating: 5,
      date: "4 days ago",
      text: "The place is absolutely gorgeous. They did the steampunk aesthetic very, very well. Their cappuccino was also good and the owner's daughter was so friendly and inviting. The story of this place is so interesting.",
      url: "",
    },
    {
      author: "Alexandru Șoimu",
      rating: 5,
      date: "9 weeks ago",
      text: "Un loc minunat cu o energie aparte. Service: 5/5. Atmosphere: 5/5.",
      url: "",
    },
    {
      author: "GabeN 1337",
      rating: 5,
      date: "10 weeks ago",
      text: "Cel mai bun cappuccino pe care l-am băut! Recomand această locație pentru oricine care vizitează piața Ovidiu. Food: 5/5. Service: 5/5. Atmosphere: 5/5.",
      url: "",
    },
    {
      author: "Alex Alexu",
      rating: 5,
      date: "3 months ago",
      text: "A cafe like no other in Romania. A pleasant atmosphere, good prices, quality service. A great meeting location.",
      url: "",
    },
    {
      author: "NB EricManevra",
      rating: 5,
      date: "3 months ago",
      text: "A 10-star cafe, very good quality coffee, impeccable service, great atmosphere!",
      url: "",
    },
    {
      author: "Petronela Onel",
      rating: 5,
      date: "5 months ago",
      text: "A place that honors the city and at the same time wins a leading place compared to many locations visited both in the country and abroad. It is distinguished by its pleasant atmosphere, original decor, service, friendliness of the staff and excellent quality of drinks, impeccable cleanliness, low prices, diverse menu, everything superlative! I recommend with confidence!",
      url: "",
    },
    {
      author: "Alina-Simona Ciciu",
      rating: 5,
      date: "6 months ago",
      text: 'The best cocktails and "improved" teas in Constanta! I highly recommend it!',
      url: "",
    },
    {
      author: "Florin Stefan",
      rating: 5,
      date: "7 months ago",
      text: "Everything is really nice, products and services, but the steampunk design is outstanding and unique. 10/10",
      url: "",
    },
    {
      author: "Alina O",
      rating: 5,
      date: "7 months ago",
      text: "The nicest location in Constanta. The coffee is great, the cocktails are made just right, and the winter teas are just what you need after a cold walk on the waterfront.",
      url: "",
    },
    {
      author: "Cornel Ionescu",
      rating: 5,
      date: "7 months ago",
      text: "Excellent experience 😘! A place not to be missed! Roxana very knowledgeable and friendly!... exceptional cocktails!... outstanding 10 👏👏👏 well dune.",
      url: "",
    },
    {
      author: "Octavian G.",
      rating: 5,
      date: "8 months ago",
      text: "Super cocktails, coffee and ambience. Jules Verne at his best...",
      url: "",
    },
    {
      author: "Shany Aélia KISFALUDY",
      rating: 5,
      date: "9 months ago",
      text: "Delicious coffee, tiramisu coffee and spiced coffee. The waiter explained the origins of the coffee used and the different blends. Very friendly. The place is amazing, the decor is fantastic.",
      url: "",
    },
  ],

  tripadvisor: [
    {
      author: "bruyndomcx ivan",
      rating: 5,
      date: "June 2025",
      title: "Nice cocktails!",
      text: "Nice cocktails! Here there is still a lot of effort to make a real tasty cocktail, with the right ingredients and proportions. The lady who served us was also incredibly friendly.",
      url: "",
    },
    {
      author: "Oana J",
      rating: 5,
      date: "May 2025",
      title: "LOVE IT!",
      text: "What a unique place! The cocktail I had was top-notch, and the setting makes you feel like you stepped into a retro-futuristic novel.",
      url: "",
    },
    {
      author: "Bogdan S",
      rating: 5,
      date: "May 2025",
      title: "Magical",
      text: "A magical corner in the Old Town! The steampunk atmosphere is absolutely fascinating, and the barista truly knows their craft. I had a perfect flat white. I’ll definitely be back!",
      url: "",
    },
    {
      author: "John C Ro",
      rating: 5,
      date: "May 2025",
      title: "A perfect coffee in a magnificent place!",
      text: "I discovered last week Hypso 25 in Piata Ovidiu, Constanta, and it was a revelation! The place is stunning—elegant, imaginative, and reminiscent of a Jules Verne submarine. The décor stands out with refined design and high-quality materials. Coffee and drinks are exceptional, carefully chosen and served to the highest standards. The staff is professional and welcoming, enhancing the overall experience. Hypso 25 isn’t just a café—it’s a beautifully crafted escape. Highly recommended!",
      url: "",
    },
    {
      author: "Stefan N",
      rating: 5,
      date: "Aug 2021",
      title: "Impeccable!",
      text: "Few places have this type of exquisiteness and personal touch like this one, with everything being at the top of the game! Service impeccable, with brand new cocktails asked on the spot, being done to perfection by the barman only by letting him know the ingredients and prices that beg you to order some more! Keep it up guys, I'll be coming back for more!",
      url: "",
    },
    {
      author: "Susan P",
      rating: 5,
      date: "Jul 2021",
      title: "Excellent location",
      text: "Was not intending on sitting at a bar, but the decorations here were absolutely stunning and drew attention. Ordered some cocktails which looked and tasted wonderful.",
      url: "",
    },
    {
      author: "Cosmin CCC",
      rating: 5,
      date: "Jun 2021",
      title: "Very good speciality coffee in steampunk bar",
      text: "Excellent coffee and cocktails place situated in old Ovidiu square. The bar offers speciality coffee from Origo Roastery. Very knowledgeable and educated bartender / barista. Friendly and professional. Highly recommended.",
      url: "",
    },
    {
      author: "Stay44083392727",
      rating: 5,
      date: "May 2025",
      title: "Good experience",
      text: "Amazing place in Constanta’s historical center. Great for meeting friends, having a glass of wine, or just enjoying some alone time.",
      url: "",
    },
    {
      author: "Sergiu B",
      rating: 5,
      date: "Aug 2021",
      title: "Special place",
      text: "A very special place and delicious drinks 👍🏻 The barman was professional and the Old Fashioned correct! Together with friends we had a great relaxing time.",
      url: "",
    },
    {
      author: "bogdan",
      rating: 5,
      date: "Aug 2019",
      title: "Good coffee, nice view!",
      text: "Been there today, had a cappuccino. Good one! The service was great, as well. And the view is just great, as I am a history enthusiast! 5*, I’ll come back anytime with pleasure.",
      url: "",
    },
    {
      author: "Vlad M",
      rating: 5,
      date: "Jul 2022",
      title: "Coffee, cocktails and good food",
      text: "One of the best coffee shops in Romania. Also, they have what it takes to make your day with beverages prepared by a well-known mixologist. When in Constanta, it is the go-to place. True value for money.",
      url: "",
    },
  ],
};
